### ISSUE TITLE
Multiple issues using arquillian

### ISSUE THREAD

**Issue by yblazart** [kumuluz/kumuluzee-testing#1]
Hello, I really want to use Kumuluzee for our little project. 
But I encounter multiple problems. My goal is to to test my services using transaction and cdi etc...

My test is UserRepositoryTest located in airsoftqg-backend-services module.

My code is here : 
 [airsoftqg copie.zip](https://github.com/kumuluz/kumuluzee-testing/files/2064799/airsoftqg.copie.zip)

To achieve that tests , in my service module, in test I add the service code to get dependencies : 

```
public class DependencyAdapter  implements MavenDependencyAppender {
    @Override
    public List<String> addLibraries() {
        MavenResolvedArtifact[] mras = Maven
                .resolver()
                .loadPomFromFile("pom.xml")
                .importRuntimeDependencies()
                .resolve()
                .withTransitivity()
                .asResolvedArtifact();


        List<String> collect = Arrays.stream(mras)
                .map(MavenArtifactInfo::getCoordinate)
                .map(c -> c.getGroupId() + ":" + c.getArtifactId() + ":" + c.getVersion())
                .collect(Collectors.toList());

        collect.forEach(System.out::println);
        return collect;
    }
}
```

First, I had to modifiy kumuluzee-testing to : 
 
- Set version to 3.0.0-SNAPSHOT
- add repositories : 
   in RequiredLibrairies 

```
        MavenRemoteRepository sprepo=MavenRemoteRepositories
                .createRemoteRepository("sprepo","http://repo.spring.io/plugins-release/","default");
        sprepo.setUpdatePolicy(MavenUpdatePolicy.UPDATE_POLICY_ALWAYS);
        resolver=resolver.withMavenCentralRepo(true).withRemoteRepo(sprepo);
```
Certainly because of some of my dependencies.

My 'version' of testing is here [kumuluzee-testing-ybl.zip](https://github.com/kumuluz/kumuluzee-testing/files/2064801/kumuluzee-testing-ybl.zip)
(1.0.0-ybl-SNAPSHOT), so to reproduce my problem, we should clean install this locally first.

I wish to add a mecanism in MavenDepencyAdapter to add the possibility to specify remote repos you want to add, my first contribution I hope.

But, when I launch the build in my project, now I get : 

PersistenceException: No Persistence provider for EntityManager named aqg_PU

Even if kumuluzee-jpa-hibernate is well added to project and listed in Maven dep mecanisn.

Is anybody can help me ?

Other point, downloading again all deps took time, surely something to improve, or isn't possible to make an embedded mode ?

Thanks for you help.

Regards.

**Comment by urbim** [comment]
Hi!

Thanks for your interest. I have taken a look at your code.

Try using EclipseLink instead of Hibernate. So instead of this in `pom.xml`:

```xml
<dependency>
    <groupId>com.kumuluz.ee</groupId>
    <artifactId>kumuluzee-jpa-hibernate</artifactId>
</dependency>
```

Use this:

```xml
<dependency>
    <groupId>com.kumuluz.ee</groupId>
    <artifactId>kumuluzee-jpa-eclipselink</artifactId>
</dependency>
```

I'm not yet sure why Hibernate doesn't work.

Also a few remarks:

In `arquillian.xml` set property `includeRequiredLibraries` to `false` instead of `MicroProfile-1.2`, since you're already adding all MicroProfile dependencies through pom scanning in your `DependencyAppender`.

In `DependencyAppender`, change `.importRuntimeDependencies()` to `.importRuntimeAndTestDependencies()` so Maven dependencies with `test` scope are added to the deployment.

As for the possibility to specify remote repos, the feature should probably be added as a separate method in `MavenDependencyAppender` class or another `ServiceLoader`type class and expose `ConfigurableMavenResolverSystem` before libraries get resolved.

Hope this helps.

**Comment by urbim** [comment]
The ability to add additional remote repositories has been added. See README for more details.

I have also tried creating a new project using Hibernate and H2 in-memory database, similar as in your project and tests are running fine. So it must be something with your dependencies or the way you are scanning and adding them to the deployments.

Best of luck.
